---
title: "2020-03-23 experiments"
output: 
  html_document: 
    keep_md: no
    toc: true
    toc_float: true
    toc_depth: 4
    collapsed: false
    theme: default
---

## Setup

### Load R libraries

```{r, message=FALSE}
library(tidyr)    # (Wickham & Henry, 2018)
library(ggplot2)  # (Wickham, 2009)
library(plyr)     # (Wickham, 2011)
library(dplyr)    # (Wickham et al., 2018)
library(cowplot)  # (Wilke, 2018)
```

## Load data

### Extract most performant organisms

```{r}
extract_max_fit <- function(data_path) {
  data <- read.csv(data_path, na.strings="NONE")
  data$matchbin_metric <- factor(data$matchbin_metric,
                                  levels=c("hamming", 
                                           "integer", 
                                            "integer-symmetric", 
                                            "hash", 
                                            "streak", 
                                            "streak-exact"))
  data$tag_mut_rate <- factor(as.numeric(data$MUT_RATE__FUNC_TAG_BF))
  return(data)
}

exp_name <- "2020-03-23"
out_dir <- "2020-03-23-step-2"
dst_data_loc <- paste("../data/",exp_name,"/step-two/dir-sig/max_fit_orgs.csv", sep="")
dst_data <- extract_max_fit(dst_data_loc)
# cst_data_loc <- paste("../data/",exp_name,"/step-two/chg-env/max_fit_orgs_100.csv", sep="")
# cst_data <- extract_max_fit(cst_data_loc)

num_replicates <- 200
```

### Extract fitness over time

```{r}
dst_fot_data_loc <- paste("../data/", exp_name, "/step-two/dir-sig/fot.csv", sep="")
dst_fot_data <- read.csv(dst_fot_data_loc, na.strings="NONE")
dst_fot_data$tag_metric <- factor(dst_fot_data$tag_metric,
                                    levels=c("hamming", 
                                             "integer", 
                                             "integer-symmetric", 
                                             "hash", 
                                             "streak", 
                                             "streak-exact"))
dst_fot_data$tag_mut_rate <- factor(as.numeric(dst_fot_data$tag_mut_rate))

# cst_fot_data_loc <- paste("../data/",exp_name,"/chg-env/fot.csv", sep="")
# cst_fot_data <- read.csv(cst_fot_data_loc, na.strings="NONE")
# cst_fot_data$matchbin_metric <- factor(cst_fot_data$matchbin_metric,
#                                     levels=c("hamming", 
#                                              "integer", 
#                                              "integer-symmetric", 
#                                              "hash", 
#                                              "streak", 
#                                              "streak-exact"))
# cst_fot_data$tag_mut_rate <- factor(as.numeric(cst_fot_data$MUT_RATE__FUNC_TAG_BF))
```

## Directional Signal Task

### Solutions x metric

```{r}
generation_cutoffs <- c(500, 1000, 3000, 5000)
exp_prefix <- "dst"
for (gen in generation_cutoffs) {
  p <- ggplot(filter(dst_data, solution=="1" & update <= gen), aes(x=matchbin_metric, fill=matchbin_metric)) +
    geom_bar(stat="count", position="dodge") +
    geom_text(stat="count", 
            mapping=aes(label=..count..), 
            position=position_dodge(0.9), vjust=0) +
    ggtitle(paste("Directional signal task - solutions\n","<= ", gen, sep="")) +
    ylim(0, num_replicates+2) +
    theme(axis.text.x=element_text(size=8)) +
    ggsave(paste("./imgs/",out_dir,"/", exp_prefix, "-solutions-",gen,".png",sep=""), width=16, height=8)
  print(p)
}
```

### Scores x metric

```{r}
exp_prefix <- "dst"
p <- ggplot(dst_data, aes(x=matchbin_metric, y=aggregate_score, fill=matchbin_metric)) +
    geom_boxplot() +
    ggtitle(paste("Directional signal task - scores", sep="")) +
    theme(axis.text.x=element_text(size=8)) +
    ggsave(paste("./imgs/",out_dir,"/", exp_prefix, "-scores.png",sep=""), width=16, height=8)
print(p)
```

### Time to solution x metric

```{r}
exp_prefix <- "dst"
p <- ggplot(dst_data, aes(x=matchbin_metric, y=update, fill=matchbin_metric)) +
    geom_boxplot() +
    geom_jitter() +
    ggtitle(paste("Directional signal task - time to solution", sep="")) +
    theme(axis.text.x=element_text(size=8)) +
    ggsave(paste("./imgs/",out_dir,"/", exp_prefix, "-time-to-solution.png",sep=""), width=16, height=8)
print(p)
```

### Fitness over time x metric

```{r}
updates <- c(10, 30, 50, 100, 300, 500, 1000, 3000, 5000)
plot_data <- filter(dst_fot_data, update %in% updates)
plot_data$update <- factor(plot_data$update)

ggplot(plot_data, aes(x=update, y=score, fill=tag_metric)) +
  geom_boxplot() +
  ggtitle("DST - score over time") +
  ggsave(paste("./imgs/",out_dir,"/dst_score_over_time_box.pdf", sep=""), width=21, height=8)
  
ggplot(filter(dst_fot_data), aes(x=update, y=score, color=tag_metric, fill=tag_metric)) +
  stat_summary(geom = "line", fun.y = mean) +
  stat_summary(geom = "ribbon", fun.data = mean_cl_boot, fun.args=list(conf.int=0.95), alpha = 0.3, color=NA) +
  ggtitle("DST - score over time") +
  ggsave(paste("./imgs/",out_dir,"/dst_score_over_time.pdf", sep=""), width=21, height=10)
```
